// Code generated by protoc-gen-go.
// source: raft.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	raft.proto

It has these top-level messages:
	AppendEntiresReq
	AppendEntriesRes
	RequestVoteReq
	RequestVoteRes
	GetReq
	GetRes
	PutReq
	PutRes
	OpenSessionReq
	OpenSessionRes
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AppendEntiresReq struct {
}

func (m *AppendEntiresReq) Reset()                    { *m = AppendEntiresReq{} }
func (m *AppendEntiresReq) String() string            { return proto.CompactTextString(m) }
func (*AppendEntiresReq) ProtoMessage()               {}
func (*AppendEntiresReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type AppendEntriesRes struct {
}

func (m *AppendEntriesRes) Reset()                    { *m = AppendEntriesRes{} }
func (m *AppendEntriesRes) String() string            { return proto.CompactTextString(m) }
func (*AppendEntriesRes) ProtoMessage()               {}
func (*AppendEntriesRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type RequestVoteReq struct {
}

func (m *RequestVoteReq) Reset()                    { *m = RequestVoteReq{} }
func (m *RequestVoteReq) String() string            { return proto.CompactTextString(m) }
func (*RequestVoteReq) ProtoMessage()               {}
func (*RequestVoteReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type RequestVoteRes struct {
}

func (m *RequestVoteRes) Reset()                    { *m = RequestVoteRes{} }
func (m *RequestVoteRes) String() string            { return proto.CompactTextString(m) }
func (*RequestVoteRes) ProtoMessage()               {}
func (*RequestVoteRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type GetReq struct {
}

func (m *GetReq) Reset()                    { *m = GetReq{} }
func (m *GetReq) String() string            { return proto.CompactTextString(m) }
func (*GetReq) ProtoMessage()               {}
func (*GetReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type GetRes struct {
}

func (m *GetRes) Reset()                    { *m = GetRes{} }
func (m *GetRes) String() string            { return proto.CompactTextString(m) }
func (*GetRes) ProtoMessage()               {}
func (*GetRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type PutReq struct {
}

func (m *PutReq) Reset()                    { *m = PutReq{} }
func (m *PutReq) String() string            { return proto.CompactTextString(m) }
func (*PutReq) ProtoMessage()               {}
func (*PutReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type PutRes struct {
}

func (m *PutRes) Reset()                    { *m = PutRes{} }
func (m *PutRes) String() string            { return proto.CompactTextString(m) }
func (*PutRes) ProtoMessage()               {}
func (*PutRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type OpenSessionReq struct {
}

func (m *OpenSessionReq) Reset()                    { *m = OpenSessionReq{} }
func (m *OpenSessionReq) String() string            { return proto.CompactTextString(m) }
func (*OpenSessionReq) ProtoMessage()               {}
func (*OpenSessionReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type OpenSessionRes struct {
	ClientID int64 `protobuf:"varint,1,opt,name=clientID" json:"clientID,omitempty"`
}

func (m *OpenSessionRes) Reset()                    { *m = OpenSessionRes{} }
func (m *OpenSessionRes) String() string            { return proto.CompactTextString(m) }
func (*OpenSessionRes) ProtoMessage()               {}
func (*OpenSessionRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *OpenSessionRes) GetClientID() int64 {
	if m != nil {
		return m.ClientID
	}
	return 0
}

func init() {
	proto.RegisterType((*AppendEntiresReq)(nil), "pb.AppendEntiresReq")
	proto.RegisterType((*AppendEntriesRes)(nil), "pb.AppendEntriesRes")
	proto.RegisterType((*RequestVoteReq)(nil), "pb.RequestVoteReq")
	proto.RegisterType((*RequestVoteRes)(nil), "pb.RequestVoteRes")
	proto.RegisterType((*GetReq)(nil), "pb.GetReq")
	proto.RegisterType((*GetRes)(nil), "pb.GetRes")
	proto.RegisterType((*PutReq)(nil), "pb.PutReq")
	proto.RegisterType((*PutRes)(nil), "pb.PutRes")
	proto.RegisterType((*OpenSessionReq)(nil), "pb.OpenSessionReq")
	proto.RegisterType((*OpenSessionRes)(nil), "pb.OpenSessionRes")
}

func init() { proto.RegisterFile("raft.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 241 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x64, 0x91, 0x31, 0x4b, 0x03, 0x41,
	0x10, 0x85, 0x89, 0x91, 0x23, 0x8c, 0x28, 0x61, 0xb0, 0x90, 0x05, 0x41, 0xae, 0xb2, 0x90, 0x2b,
	0x22, 0x56, 0x56, 0x82, 0x12, 0xc4, 0xc2, 0xb0, 0x42, 0xfa, 0x9c, 0x4e, 0x60, 0x41, 0x76, 0x37,
	0x3b, 0x73, 0x8d, 0xe0, 0x7f, 0x97, 0xd9, 0x4b, 0x4c, 0xf6, 0xd2, 0xbd, 0xfb, 0xde, 0x70, 0xf3,
	0xe6, 0x2d, 0x40, 0x5a, 0xad, 0xa5, 0x89, 0x29, 0x48, 0xc0, 0x93, 0xd8, 0xd6, 0x08, 0xd3, 0xa7,
	0x18, 0xc9, 0x7f, 0xbd, 0x78, 0x71, 0x89, 0xd8, 0xd2, 0xa6, 0x60, 0xc9, 0x29, 0xe3, 0x7a, 0x0a,
	0x17, 0x96, 0x36, 0x1d, 0xb1, 0x2c, 0x83, 0x90, 0x4e, 0x0d, 0x09, 0xd7, 0x13, 0xa8, 0xe6, 0x24,
	0xea, 0xed, 0x54, 0x66, 0x8b, 0x6e, 0xc7, 0xb2, 0xca, 0xff, 0x7a, 0x8f, 0xe4, 0x3f, 0x88, 0xd9,
	0x05, 0xaf, 0xde, 0xdd, 0x80, 0x30, 0x1a, 0x98, 0x7c, 0x7e, 0x3b, 0xf2, 0xf2, 0xfa, 0x7c, 0x35,
	0xba, 0x19, 0xdd, 0x8e, 0xed, 0xff, 0xf7, 0xec, 0x07, 0x4e, 0xed, 0x6a, 0x2d, 0xf8, 0x00, 0x67,
	0x07, 0x09, 0x10, 0x9b, 0xd8, 0x36, 0x65, 0x48, 0x73, 0xcc, 0x18, 0x1f, 0xe1, 0xbc, 0x38, 0x19,
	0x2f, 0x75, 0x68, 0xd8, 0x82, 0x29, 0xe9, 0xb6, 0x87, 0xd9, 0x2f, 0x54, 0xba, 0xfb, 0x6d, 0xa9,
	0xdb, 0x0f, 0x32, 0xf7, 0xdb, 0xcb, 0xb3, 0xcc, 0x31, 0x63, 0xbc, 0x86, 0xf1, 0xa2, 0x13, 0x04,
	0xb5, 0xfa, 0x66, 0xcc, 0x5e, 0x67, 0x7b, 0x4e, 0x5b, 0xbb, 0x2f, 0xd3, 0xec, 0x35, 0xb7, 0x55,
	0x7e, 0xb9, 0xfb, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x33, 0x61, 0x94, 0x1d, 0xc7, 0x01, 0x00,
	0x00,
}
