// Code generated by protoc-gen-go.
// source: raftkv.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	raftkv.proto

It has these top-level messages:
	KVCommand
	Session
	GetReq
	GetRes
	PutReq
	PutRes
	OpenSessionReq
	OpenSessionRes
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CommandType int32

const (
	CommandType_Noop CommandType = 0
	CommandType_Get  CommandType = 1
	CommandType_Put  CommandType = 2
)

var CommandType_name = map[int32]string{
	0: "Noop",
	1: "Get",
	2: "Put",
}
var CommandType_value = map[string]int32{
	"Noop": 0,
	"Get":  1,
	"Put":  2,
}

func (x CommandType) String() string {
	return proto.EnumName(CommandType_name, int32(x))
}
func (CommandType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Status int32

const (
	Status_OK        Status = 0
	Status_Timeout   Status = 1
	Status_NoSuchKey Status = 2
	Status_NotLeader Status = 3
	Status_NoSession Status = 4
)

var Status_name = map[int32]string{
	0: "OK",
	1: "Timeout",
	2: "NoSuchKey",
	3: "NotLeader",
	4: "NoSession",
}
var Status_value = map[string]int32{
	"OK":        0,
	"Timeout":   1,
	"NoSuchKey": 2,
	"NotLeader": 3,
	"NoSession": 4,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}
func (Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// command for KV, it will be replicated to peers, stored in log, and applied to KVStorage
type KVCommand struct {
	CmdType CommandType `protobuf:"varint,1,opt,name=cmd_type,json=cmdType,enum=pb.CommandType" json:"cmd_type,omitempty"`
	// Types that are valid to be assigned to Command:
	//	*KVCommand_GetCommand
	//	*KVCommand_PutCommand
	//	*KVCommand_Noop
	Command   isKVCommand_Command        `protobuf_oneof:"command"`
	Term      int32                      `protobuf:"varint,5,opt,name=term" json:"term,omitempty"`
	Index     int32                      `protobuf:"varint,6,opt,name=index" json:"index,omitempty"`
	Timestamp *google_protobuf.Timestamp `protobuf:"bytes,7,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *KVCommand) Reset()                    { *m = KVCommand{} }
func (m *KVCommand) String() string            { return proto.CompactTextString(m) }
func (*KVCommand) ProtoMessage()               {}
func (*KVCommand) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type isKVCommand_Command interface {
	isKVCommand_Command()
}

type KVCommand_GetCommand struct {
	GetCommand *GetReq `protobuf:"bytes,2,opt,name=get_command,json=getCommand,oneof"`
}
type KVCommand_PutCommand struct {
	PutCommand *PutReq `protobuf:"bytes,3,opt,name=put_command,json=putCommand,oneof"`
}
type KVCommand_Noop struct {
	Noop []byte `protobuf:"bytes,4,opt,name=noop,proto3,oneof"`
}

func (*KVCommand_GetCommand) isKVCommand_Command() {}
func (*KVCommand_PutCommand) isKVCommand_Command() {}
func (*KVCommand_Noop) isKVCommand_Command()       {}

func (m *KVCommand) GetCommand() isKVCommand_Command {
	if m != nil {
		return m.Command
	}
	return nil
}

func (m *KVCommand) GetCmdType() CommandType {
	if m != nil {
		return m.CmdType
	}
	return CommandType_Noop
}

func (m *KVCommand) GetGetCommand() *GetReq {
	if x, ok := m.GetCommand().(*KVCommand_GetCommand); ok {
		return x.GetCommand
	}
	return nil
}

func (m *KVCommand) GetPutCommand() *PutReq {
	if x, ok := m.GetCommand().(*KVCommand_PutCommand); ok {
		return x.PutCommand
	}
	return nil
}

func (m *KVCommand) GetNoop() []byte {
	if x, ok := m.GetCommand().(*KVCommand_Noop); ok {
		return x.Noop
	}
	return nil
}

func (m *KVCommand) GetTerm() int32 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *KVCommand) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *KVCommand) GetTimestamp() *google_protobuf.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*KVCommand) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _KVCommand_OneofMarshaler, _KVCommand_OneofUnmarshaler, _KVCommand_OneofSizer, []interface{}{
		(*KVCommand_GetCommand)(nil),
		(*KVCommand_PutCommand)(nil),
		(*KVCommand_Noop)(nil),
	}
}

func _KVCommand_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*KVCommand)
	// command
	switch x := m.Command.(type) {
	case *KVCommand_GetCommand:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.GetCommand); err != nil {
			return err
		}
	case *KVCommand_PutCommand:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.PutCommand); err != nil {
			return err
		}
	case *KVCommand_Noop:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		b.EncodeRawBytes(x.Noop)
	case nil:
	default:
		return fmt.Errorf("KVCommand.Command has unexpected type %T", x)
	}
	return nil
}

func _KVCommand_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*KVCommand)
	switch tag {
	case 2: // command.get_command
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GetReq)
		err := b.DecodeMessage(msg)
		m.Command = &KVCommand_GetCommand{msg}
		return true, err
	case 3: // command.put_command
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PutReq)
		err := b.DecodeMessage(msg)
		m.Command = &KVCommand_PutCommand{msg}
		return true, err
	case 4: // command.noop
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeRawBytes(true)
		m.Command = &KVCommand_Noop{x}
		return true, err
	default:
		return false, nil
	}
}

func _KVCommand_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*KVCommand)
	// command
	switch x := m.Command.(type) {
	case *KVCommand_GetCommand:
		s := proto.Size(x.GetCommand)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *KVCommand_PutCommand:
		s := proto.Size(x.PutCommand)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *KVCommand_Noop:
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Noop)))
		n += len(x.Noop)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Session struct {
	ClientId int64  `protobuf:"varint,1,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
	Sn       int64  `protobuf:"varint,2,opt,name=sn" json:"sn,omitempty"`
	LogId    string `protobuf:"bytes,3,opt,name=log_id,json=logId" json:"log_id,omitempty"`
}

func (m *Session) Reset()                    { *m = Session{} }
func (m *Session) String() string            { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()               {}
func (*Session) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Session) GetClientId() int64 {
	if m != nil {
		return m.ClientId
	}
	return 0
}

func (m *Session) GetSn() int64 {
	if m != nil {
		return m.Sn
	}
	return 0
}

func (m *Session) GetLogId() string {
	if m != nil {
		return m.LogId
	}
	return ""
}

type GetReq struct {
	Session *Session `protobuf:"bytes,1,opt,name=session" json:"session,omitempty"`
	Key     string   `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
}

func (m *GetReq) Reset()                    { *m = GetReq{} }
func (m *GetReq) String() string            { return proto.CompactTextString(m) }
func (*GetReq) ProtoMessage()               {}
func (*GetReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetReq) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *GetReq) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GetRes struct {
	Status Status `protobuf:"varint,1,opt,name=status,enum=pb.Status" json:"status,omitempty"`
	Value  string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *GetRes) Reset()                    { *m = GetRes{} }
func (m *GetRes) String() string            { return proto.CompactTextString(m) }
func (*GetRes) ProtoMessage()               {}
func (*GetRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetRes) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_OK
}

func (m *GetRes) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type PutReq struct {
	Session *Session `protobuf:"bytes,1,opt,name=session" json:"session,omitempty"`
	Key     string   `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
	Value   string   `protobuf:"bytes,3,opt,name=value" json:"value,omitempty"`
}

func (m *PutReq) Reset()                    { *m = PutReq{} }
func (m *PutReq) String() string            { return proto.CompactTextString(m) }
func (*PutReq) ProtoMessage()               {}
func (*PutReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *PutReq) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *PutReq) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *PutReq) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type PutRes struct {
	Status Status `protobuf:"varint,1,opt,name=status,enum=pb.Status" json:"status,omitempty"`
}

func (m *PutRes) Reset()                    { *m = PutRes{} }
func (m *PutRes) String() string            { return proto.CompactTextString(m) }
func (*PutRes) ProtoMessage()               {}
func (*PutRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *PutRes) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_OK
}

type OpenSessionReq struct {
	Session *Session `protobuf:"bytes,1,opt,name=session" json:"session,omitempty"`
}

func (m *OpenSessionReq) Reset()                    { *m = OpenSessionReq{} }
func (m *OpenSessionReq) String() string            { return proto.CompactTextString(m) }
func (*OpenSessionReq) ProtoMessage()               {}
func (*OpenSessionReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *OpenSessionReq) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

type OpenSessionRes struct {
	ClientId int64 `protobuf:"varint,1,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
}

func (m *OpenSessionRes) Reset()                    { *m = OpenSessionRes{} }
func (m *OpenSessionRes) String() string            { return proto.CompactTextString(m) }
func (*OpenSessionRes) ProtoMessage()               {}
func (*OpenSessionRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *OpenSessionRes) GetClientId() int64 {
	if m != nil {
		return m.ClientId
	}
	return 0
}

func init() {
	proto.RegisterType((*KVCommand)(nil), "pb.KVCommand")
	proto.RegisterType((*Session)(nil), "pb.Session")
	proto.RegisterType((*GetReq)(nil), "pb.GetReq")
	proto.RegisterType((*GetRes)(nil), "pb.GetRes")
	proto.RegisterType((*PutReq)(nil), "pb.PutReq")
	proto.RegisterType((*PutRes)(nil), "pb.PutRes")
	proto.RegisterType((*OpenSessionReq)(nil), "pb.OpenSessionReq")
	proto.RegisterType((*OpenSessionRes)(nil), "pb.OpenSessionRes")
	proto.RegisterEnum("pb.CommandType", CommandType_name, CommandType_value)
	proto.RegisterEnum("pb.Status", Status_name, Status_value)
}

func init() { proto.RegisterFile("raftkv.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 525 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x53, 0x51, 0x8b, 0xd3, 0x40,
	0x10, 0x6e, 0x92, 0x36, 0x69, 0x26, 0x67, 0x0d, 0xc3, 0x09, 0xa1, 0x22, 0x96, 0x80, 0x50, 0x8b,
	0xcd, 0x41, 0x45, 0xf4, 0xd5, 0xf3, 0xa1, 0x77, 0x56, 0xef, 0x8e, 0xed, 0x71, 0x3e, 0x96, 0xb4,
	0xd9, 0xc6, 0x72, 0x4d, 0x76, 0xed, 0x6e, 0x0e, 0xfb, 0xe0, 0x1f, 0xf1, 0xd7, 0x4a, 0x76, 0x93,
	0x4b, 0x55, 0x90, 0xc3, 0xb7, 0x99, 0xf9, 0xbe, 0x7e, 0xfb, 0xcd, 0x97, 0x29, 0x1c, 0xed, 0xe2,
	0xb5, 0xbc, 0xbd, 0x8b, 0xf8, 0x8e, 0x49, 0x86, 0x26, 0x5f, 0xf6, 0x9f, 0xa7, 0x8c, 0xa5, 0x5b,
	0x7a, 0xa2, 0x26, 0xcb, 0x62, 0x7d, 0x22, 0x37, 0x19, 0x15, 0x32, 0xce, 0xb8, 0x26, 0x85, 0x3f,
	0x4d, 0x70, 0x67, 0x37, 0x1f, 0x58, 0x96, 0xc5, 0x79, 0x82, 0x23, 0xe8, 0xae, 0xb2, 0x64, 0x21,
	0xf7, 0x9c, 0x06, 0xc6, 0xc0, 0x18, 0xf6, 0x26, 0x8f, 0x23, 0xbe, 0x8c, 0x2a, 0xf8, 0x7a, 0xcf,
	0x29, 0x71, 0x56, 0x99, 0x2a, 0x70, 0x0c, 0x5e, 0x4a, 0xe5, 0x62, 0xa5, 0xb1, 0xc0, 0x1c, 0x18,
	0x43, 0x6f, 0x02, 0x25, 0x7d, 0x4a, 0x25, 0xa1, 0xdf, 0xce, 0x5a, 0x04, 0x52, 0x2a, 0x6b, 0xe9,
	0x31, 0x78, 0xbc, 0x68, 0xe8, 0x56, 0x43, 0xbf, 0x2a, 0x6a, 0x3a, 0x2f, 0xee, 0xe9, 0xc7, 0xd0,
	0xce, 0x19, 0xe3, 0x41, 0x7b, 0x60, 0x0c, 0x8f, 0xce, 0x5a, 0x44, 0x75, 0x88, 0xd0, 0x96, 0x74,
	0x97, 0x05, 0x9d, 0x81, 0x31, 0xec, 0x10, 0x55, 0xe3, 0x31, 0x74, 0x36, 0x79, 0x42, 0xbf, 0x07,
	0xb6, 0x1a, 0xea, 0x06, 0xdf, 0x81, 0x7b, 0xbf, 0x6a, 0xe0, 0xa8, 0xc7, 0xfa, 0x91, 0x0e, 0x23,
	0xaa, 0xc3, 0x88, 0xae, 0x6b, 0x06, 0x69, 0xc8, 0xa7, 0x2e, 0x38, 0x95, 0xc9, 0xf0, 0x33, 0x38,
	0x73, 0x2a, 0xc4, 0x86, 0xe5, 0xf8, 0x14, 0xdc, 0xd5, 0x76, 0x43, 0x73, 0xb9, 0xd8, 0x24, 0x2a,
	0x1a, 0x8b, 0x74, 0xf5, 0xe0, 0x3c, 0xc1, 0x1e, 0x98, 0x22, 0x57, 0x09, 0x58, 0xc4, 0x14, 0x39,
	0x3e, 0x01, 0x7b, 0xcb, 0xd2, 0x92, 0x59, 0xae, 0xe9, 0x92, 0xce, 0x96, 0xa5, 0xe7, 0x49, 0xf8,
	0x1e, 0x6c, 0x1d, 0x0d, 0xbe, 0x00, 0x47, 0x68, 0x61, 0xa5, 0xe5, 0x4d, 0xbc, 0x32, 0x88, 0xea,
	0x2d, 0x52, 0x63, 0xe8, 0x83, 0x75, 0x4b, 0xf7, 0x4a, 0xd8, 0x25, 0x65, 0x19, 0x9e, 0x56, 0x12,
	0x02, 0x43, 0xb0, 0x85, 0x8c, 0x65, 0x21, 0xaa, 0x0f, 0xa5, 0xa2, 0x9c, 0xab, 0x09, 0xa9, 0x90,
	0x32, 0x9a, 0xbb, 0x78, 0x5b, 0xd0, 0x4a, 0x41, 0x37, 0xe1, 0x17, 0xb0, 0x75, 0xe4, 0xff, 0x6d,
	0xa3, 0x11, 0xb6, 0x0e, 0x85, 0x5f, 0x55, 0xc2, 0x0f, 0x32, 0x17, 0xbe, 0x85, 0xde, 0x25, 0xa7,
	0x79, 0xfd, 0xda, 0x83, 0xed, 0x84, 0xe3, 0x3f, 0x7e, 0x28, 0xfe, 0xf9, 0x71, 0x46, 0x2f, 0xc1,
	0x3b, 0xb8, 0x5f, 0xec, 0x42, 0xfb, 0x82, 0x31, 0xee, 0xb7, 0xd0, 0x01, 0x6b, 0x4a, 0xa5, 0x6f,
	0x94, 0xc5, 0x55, 0x21, 0x7d, 0x73, 0xf4, 0x11, 0x6c, 0x6d, 0x12, 0x6d, 0x30, 0x2f, 0x67, 0x7e,
	0x0b, 0x3d, 0x70, 0xca, 0x23, 0x61, 0x45, 0xc9, 0x7b, 0x04, 0xee, 0x05, 0x9b, 0x17, 0xab, 0xaf,
	0x33, 0xba, 0xf7, 0x4d, 0xdd, 0xca, 0x4f, 0x34, 0x4e, 0xe8, 0xce, 0xb7, 0x2a, 0x54, 0x9b, 0xf2,
	0xdb, 0x93, 0x1f, 0x60, 0x93, 0x78, 0x2d, 0x67, 0x37, 0xf8, 0x06, 0xbc, 0x03, 0xbf, 0x88, 0xe5,
	0x52, 0xbf, 0x6f, 0xde, 0xff, 0x7b, 0x26, 0xf0, 0x99, 0x72, 0x85, 0x07, 0x7f, 0x91, 0x7e, 0x53,
	0x2b, 0x78, 0x4a, 0x2b, 0x58, 0x5f, 0x55, 0xbf, 0xa9, 0xc5, 0xd2, 0x56, 0x47, 0xfe, 0xfa, 0x57,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x57, 0x43, 0x30, 0x03, 0x13, 0x04, 0x00, 0x00,
}
