// Code generated by protoc-gen-go.
// source: raft.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	raft.proto
	raftkv.proto

It has these top-level messages:
	AppendEntriesReq
	AppendEntriesRes
	RequestVoteReq
	RequestVoteRes
	KVCommand
	Session
	GetReq
	GetRes
	PutReq
	PutRes
	OpenSessionReq
	OpenSessionRes
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AppendEntriesReq struct {
	Term         int32        `protobuf:"varint,1,opt,name=term" json:"term,omitempty"`
	LeaderId     int32        `protobuf:"varint,2,opt,name=leader_id,json=leaderId" json:"leader_id,omitempty"`
	PrevLogIndex int32        `protobuf:"varint,3,opt,name=prev_log_index,json=prevLogIndex" json:"prev_log_index,omitempty"`
	PrevLogTerm  int32        `protobuf:"varint,4,opt,name=prev_log_term,json=prevLogTerm" json:"prev_log_term,omitempty"`
	LogEntries   []*KVCommand `protobuf:"bytes,5,rep,name=log_entries,json=logEntries" json:"log_entries,omitempty"`
	LeaderCommit int32        `protobuf:"varint,6,opt,name=leader_commit,json=leaderCommit" json:"leader_commit,omitempty"`
}

func (m *AppendEntriesReq) Reset()                    { *m = AppendEntriesReq{} }
func (m *AppendEntriesReq) String() string            { return proto.CompactTextString(m) }
func (*AppendEntriesReq) ProtoMessage()               {}
func (*AppendEntriesReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AppendEntriesReq) GetTerm() int32 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *AppendEntriesReq) GetLeaderId() int32 {
	if m != nil {
		return m.LeaderId
	}
	return 0
}

func (m *AppendEntriesReq) GetPrevLogIndex() int32 {
	if m != nil {
		return m.PrevLogIndex
	}
	return 0
}

func (m *AppendEntriesReq) GetPrevLogTerm() int32 {
	if m != nil {
		return m.PrevLogTerm
	}
	return 0
}

func (m *AppendEntriesReq) GetLogEntries() []*KVCommand {
	if m != nil {
		return m.LogEntries
	}
	return nil
}

func (m *AppendEntriesReq) GetLeaderCommit() int32 {
	if m != nil {
		return m.LeaderCommit
	}
	return 0
}

type AppendEntriesRes struct {
	Term    int32 `protobuf:"varint,1,opt,name=term" json:"term,omitempty"`
	Success bool  `protobuf:"varint,2,opt,name=success" json:"success,omitempty"`
}

func (m *AppendEntriesRes) Reset()                    { *m = AppendEntriesRes{} }
func (m *AppendEntriesRes) String() string            { return proto.CompactTextString(m) }
func (*AppendEntriesRes) ProtoMessage()               {}
func (*AppendEntriesRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AppendEntriesRes) GetTerm() int32 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *AppendEntriesRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type RequestVoteReq struct {
	Term         int32 `protobuf:"varint,1,opt,name=term" json:"term,omitempty"`
	CandidateId  int32 `protobuf:"varint,2,opt,name=candidate_id,json=candidateId" json:"candidate_id,omitempty"`
	LastLogIndex int32 `protobuf:"varint,3,opt,name=last_log_index,json=lastLogIndex" json:"last_log_index,omitempty"`
	LastLogTerm  int32 `protobuf:"varint,4,opt,name=last_log_term,json=lastLogTerm" json:"last_log_term,omitempty"`
}

func (m *RequestVoteReq) Reset()                    { *m = RequestVoteReq{} }
func (m *RequestVoteReq) String() string            { return proto.CompactTextString(m) }
func (*RequestVoteReq) ProtoMessage()               {}
func (*RequestVoteReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *RequestVoteReq) GetTerm() int32 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *RequestVoteReq) GetCandidateId() int32 {
	if m != nil {
		return m.CandidateId
	}
	return 0
}

func (m *RequestVoteReq) GetLastLogIndex() int32 {
	if m != nil {
		return m.LastLogIndex
	}
	return 0
}

func (m *RequestVoteReq) GetLastLogTerm() int32 {
	if m != nil {
		return m.LastLogTerm
	}
	return 0
}

type RequestVoteRes struct {
	Term        int32 `protobuf:"varint,1,opt,name=term" json:"term,omitempty"`
	VoteGranted bool  `protobuf:"varint,2,opt,name=vote_granted,json=voteGranted" json:"vote_granted,omitempty"`
}

func (m *RequestVoteRes) Reset()                    { *m = RequestVoteRes{} }
func (m *RequestVoteRes) String() string            { return proto.CompactTextString(m) }
func (*RequestVoteRes) ProtoMessage()               {}
func (*RequestVoteRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *RequestVoteRes) GetTerm() int32 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *RequestVoteRes) GetVoteGranted() bool {
	if m != nil {
		return m.VoteGranted
	}
	return false
}

func init() {
	proto.RegisterType((*AppendEntriesReq)(nil), "pb.AppendEntriesReq")
	proto.RegisterType((*AppendEntriesRes)(nil), "pb.AppendEntriesRes")
	proto.RegisterType((*RequestVoteReq)(nil), "pb.RequestVoteReq")
	proto.RegisterType((*RequestVoteRes)(nil), "pb.RequestVoteRes")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Raft service

type RaftClient interface {
	RequestVote(ctx context.Context, in *RequestVoteReq, opts ...grpc.CallOption) (*RequestVoteRes, error)
	AppendEntries(ctx context.Context, in *AppendEntriesReq, opts ...grpc.CallOption) (*AppendEntriesRes, error)
}

type raftClient struct {
	cc *grpc.ClientConn
}

func NewRaftClient(cc *grpc.ClientConn) RaftClient {
	return &raftClient{cc}
}

func (c *raftClient) RequestVote(ctx context.Context, in *RequestVoteReq, opts ...grpc.CallOption) (*RequestVoteRes, error) {
	out := new(RequestVoteRes)
	err := grpc.Invoke(ctx, "/pb.Raft/RequestVote", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftClient) AppendEntries(ctx context.Context, in *AppendEntriesReq, opts ...grpc.CallOption) (*AppendEntriesRes, error) {
	out := new(AppendEntriesRes)
	err := grpc.Invoke(ctx, "/pb.Raft/AppendEntries", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Raft service

type RaftServer interface {
	RequestVote(context.Context, *RequestVoteReq) (*RequestVoteRes, error)
	AppendEntries(context.Context, *AppendEntriesReq) (*AppendEntriesRes, error)
}

func RegisterRaftServer(s *grpc.Server, srv RaftServer) {
	s.RegisterService(&_Raft_serviceDesc, srv)
}

func _Raft_RequestVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestVoteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftServer).RequestVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Raft/RequestVote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftServer).RequestVote(ctx, req.(*RequestVoteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raft_AppendEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendEntriesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftServer).AppendEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Raft/AppendEntries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftServer).AppendEntries(ctx, req.(*AppendEntriesReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Raft_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Raft",
	HandlerType: (*RaftServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestVote",
			Handler:    _Raft_RequestVote_Handler,
		},
		{
			MethodName: "AppendEntries",
			Handler:    _Raft_AppendEntries_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "raft.proto",
}

func init() { proto.RegisterFile("raft.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 354 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x92, 0xbd, 0x6e, 0xea, 0x30,
	0x18, 0x86, 0x09, 0x7f, 0x87, 0xf3, 0x85, 0xa0, 0x23, 0xeb, 0x0c, 0x11, 0x67, 0xe1, 0xa4, 0x1d,
	0x98, 0x32, 0xd0, 0xa1, 0x53, 0xa5, 0x56, 0xa8, 0x42, 0xa8, 0x9d, 0xa2, 0x8a, 0x35, 0x32, 0xf1,
	0x47, 0x14, 0x35, 0x89, 0x83, 0x6d, 0x50, 0xa7, 0xde, 0x43, 0x6f, 0xb1, 0x57, 0x52, 0xd9, 0x4e,
	0x29, 0xbf, 0x9b, 0xfd, 0xf8, 0x95, 0xfd, 0xbd, 0x8f, 0x0c, 0x20, 0xe8, 0x4a, 0x85, 0x95, 0xe0,
	0x8a, 0x93, 0x66, 0xb5, 0x1c, 0xf6, 0xf5, 0xfe, 0x75, 0x6b, 0x49, 0xf0, 0xe9, 0xc0, 0x9f, 0x87,
	0xaa, 0xc2, 0x92, 0x3d, 0x96, 0x4a, 0x64, 0x28, 0x23, 0x5c, 0x13, 0x02, 0x6d, 0x85, 0xa2, 0xf0,
	0x9d, 0x91, 0x33, 0xee, 0x44, 0x66, 0x4d, 0xfe, 0xc1, 0xef, 0x1c, 0x29, 0x43, 0x11, 0x67, 0xcc,
	0x6f, 0x9a, 0x83, 0x9e, 0x05, 0x73, 0x46, 0xae, 0x61, 0x50, 0x09, 0xdc, 0xc6, 0x39, 0x4f, 0xe3,
	0xac, 0x64, 0xf8, 0xe6, 0xb7, 0x4c, 0xa2, 0xaf, 0xe9, 0x33, 0x4f, 0xe7, 0x9a, 0x91, 0x00, 0xbc,
	0x5d, 0xca, 0xdc, 0xdf, 0x36, 0x21, 0xb7, 0x0e, 0xbd, 0xe8, 0x67, 0x42, 0x70, 0xf5, 0x31, 0xda,
	0x61, 0xfc, 0xce, 0xa8, 0x35, 0x76, 0x27, 0x5e, 0x58, 0x2d, 0xc3, 0xa7, 0xc5, 0x94, 0x17, 0x05,
	0x2d, 0x59, 0x04, 0x39, 0x4f, 0xeb, 0x69, 0xc9, 0x15, 0x78, 0xf5, 0x58, 0x09, 0x2f, 0x8a, 0x4c,
	0xf9, 0x5d, 0xfb, 0xb0, 0x85, 0x53, 0xc3, 0x82, 0xfb, 0x93, 0x8e, 0xf2, 0x6c, 0x47, 0x1f, 0x7e,
	0xc9, 0x4d, 0x92, 0xa0, 0x94, 0xa6, 0x61, 0x2f, 0xfa, 0xde, 0x06, 0x1f, 0x0e, 0x0c, 0x22, 0x5c,
	0x6f, 0x50, 0xaa, 0x05, 0x57, 0x78, 0x49, 0xd2, 0x7f, 0xe8, 0x27, 0xb4, 0x64, 0x19, 0xa3, 0x0a,
	0x7f, 0x3c, 0xb9, 0x3b, 0x66, 0x55, 0xe5, 0x54, 0xaa, 0x53, 0x55, 0x9a, 0xee, 0xab, 0xda, 0xa5,
	0xf6, 0x55, 0xd5, 0x21, 0xad, 0x2a, 0x98, 0x1d, 0x8d, 0x24, 0x2f, 0x8d, 0xb4, 0xe5, 0x0a, 0xe3,
	0x54, 0xd0, 0x52, 0x21, 0xab, 0x8b, 0xb9, 0x9a, 0xcd, 0x2c, 0x9a, 0xbc, 0x43, 0x3b, 0xa2, 0x2b,
	0x45, 0x6e, 0xc1, 0xdd, 0xbb, 0x90, 0x10, 0x6d, 0xfd, 0xb0, 0xf4, 0xf0, 0x94, 0xc9, 0xa0, 0x41,
	0xee, 0xc0, 0x3b, 0xf0, 0x4b, 0xfe, 0xea, 0xd8, 0xf1, 0xb7, 0x1a, 0x9e, 0xa3, 0x32, 0x68, 0x2c,
	0xbb, 0xe6, 0x2b, 0xde, 0x7c, 0x05, 0x00, 0x00, 0xff, 0xff, 0x62, 0x6d, 0x6a, 0x4a, 0xaa, 0x02,
	0x00, 0x00,
}
